//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Classes.DictionariesResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShapesReport_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShapesReport_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Classes.DictionariesResources.ShapesReport_es", typeof(ShapesReport_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} | Área {2} | Perímetro {3} &lt;br/&gt;.
        /// </summary>
        public static string BodyResumeLine {
            get {
                return ResourceManager.GetString("BodyResumeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL:&lt;br/&gt;.
        /// </summary>
        public static string FooterTotal {
            get {
                return ResourceManager.GetString("FooterTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área {0}.
        /// </summary>
        public static string FooterTotalArea {
            get {
                return ResourceManager.GetString("FooterTotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perímetro {0} .
        /// </summary>
        public static string FooterTotalPerimeter {
            get {
                return ResourceManager.GetString("FooterTotalPerimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} formas .
        /// </summary>
        public static string FooterTotalShapes {
            get {
                return ResourceManager.GetString("FooterTotalShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Reporte de Formas&lt;/h1&gt;.
        /// </summary>
        public static string HeaderReportName {
            get {
                return ResourceManager.GetString("HeaderReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Lista vacía de formas!&lt;/h1&gt;.
        /// </summary>
        public static string ListEmpty {
            get {
                return ResourceManager.GetString("ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculos.
        /// </summary>
        public static string ShapePluralCircle {
            get {
                return ResourceManager.GetString("ShapePluralCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectángulos.
        /// </summary>
        public static string ShapePluralRectangle {
            get {
                return ResourceManager.GetString("ShapePluralRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrados.
        /// </summary>
        public static string ShapePluralSquare {
            get {
                return ResourceManager.GetString("ShapePluralSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecios.
        /// </summary>
        public static string ShapePluralTrapeze {
            get {
                return ResourceManager.GetString("ShapePluralTrapeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulos.
        /// </summary>
        public static string ShapePluralTriangle {
            get {
                return ResourceManager.GetString("ShapePluralTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculo.
        /// </summary>
        public static string ShapeSingularCircle {
            get {
                return ResourceManager.GetString("ShapeSingularCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectángulo.
        /// </summary>
        public static string ShapeSingularRectangle {
            get {
                return ResourceManager.GetString("ShapeSingularRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        public static string ShapeSingularSquare {
            get {
                return ResourceManager.GetString("ShapeSingularSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecio.
        /// </summary>
        public static string ShapeSingularTrapeze {
            get {
                return ResourceManager.GetString("ShapeSingularTrapeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulo.
        /// </summary>
        public static string ShapeSingularTriangle {
            get {
                return ResourceManager.GetString("ShapeSingularTriangle", resourceCulture);
            }
        }
    }
}
